### PR TITLE
versions: update kernel to linux-container-4.9.34-75

### LINKED ISSUE #1023: versions: update to  linux-container-4.9.34-75
The kernel was updated to  linux-container-4.9.34-75 it is need to update it and  image.

### PR DESCRIPTION
**Pull request by jcvenegas**
This patch update kernel to 4.9.34-75 and container
image to 16160.

Fixes #1023

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
@gorozco1

**Comment by jodh-intel** [comment]
lgtm

**Comment by gorozco1** [comment]
👍

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
