### PR TITLE
release: version 2.2.2

### PR DESCRIPTION
**Pull request by jcvenegas**
# Release 2.2.2

## Changes
- artifacts: Remove OBS common artifacsts between 2.x and 3.x
- versions: Update kernel and image versions
- Tests: Change nginx image for swarm tests
- install: Extract autoconf-archive install to separate script

## Shortlog
ef8144e artifacts: Remove OBS common artifacsts between 2.x and 3.x
73e28fe versions: Update kernel and image versions
3a9e3d7 Tests: Change nginx image for swarm tests
82cfb1f install: Extract autoconf-archive install to separate script

## Compatibility with Docker
Clear Containers 2.2.2 is compatible with Docker v17.05.0-ce
## OCI Runtime Specification
Clear Containers 2.2.2 support the OCI Runtime Specification [1.0.0-rc5][ocispec]
## Clear Linux Containers image
Clear Containers 2.2.2 requires at least Clear Linux containers image [16180][clearlinuximage]
## Clear Linux Containers Kernel
Clear Containers 2.2.2 requires at least Clear Linux Containers  kernel 4.9.35-76

# Installation
- [Centos][centos]
- [Ubuntu][ubuntu]
- [Fedora][fedora]
- [Clear Linux][clearlinux]

# Issues & limitations
- Qemu segfault (free(): invalid pointer) running dnf install #669
- DNS Resolution in Swarm #854
- docker rm -f reports 'Driver devicemapper failed to remove root filesystem' #795

[centos]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Centos-7.md
[ubuntu]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Ubuntu.md
[fedora]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Fedora.md
[clearlinux]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-ClearLinux.md
[clearlinuximage]: https://download.clearlinux.org/releases/16180/clear/clear-16180-containers.img.xz
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5

Fixes: #1033

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
@chavafg obs packages ready for teststing http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-staging/Fedora_26/x86_64/

**Comment by gorozco1** [comment]
lgtm

**Comment by jcvenegas** [comment]
obs packages tested:
```
cc-oci-runtime:          2.2.1 + 6c44e89
clear-containers image:  clear-16180-containers.img
clear-containers kernel: vmlinux-4.9.35-62.container 
qemu-lite:               2.7.1 + git.741f430-4.1 
```

**Comment by amshinde** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
