### PR TITLE
proxy & hyperstart logging

### PR DESCRIPTION
**Pull request by dlespiau**
This PR makes the proxy able to extract the hyperstart logs out of the VM and display then along with the usual proxy tracing, that should help us debug some of the weird interactions we still have with hyperstart:

I haven't added the console path to the state on purpose as I'm not really sure it belongs to the runtime state (I'm not too sure ctl and io socket belong there either tbh). It may belong to a potential proxy state in case we want to upgrade the proxy for instance and need to read back the proxy state from disk.

The result looks like:

```
$ sudo ./cc-proxy -v 3
I1202 11:44:36.079095   10204 proxy.go:332] proxy started
I1202 11:44:44.922280   10204 proxy.go:63] [client #1] client connected
I1202 11:44:45.124991   10204 proxy.go:73] [client #1] hello(containerId=0241be9e1ea9d12def00aebaaf71e736b7b0a613ce3a6167f39e7f5dcb524b0a,ctlSerial=/var/run/cc-oci-runtime/0241be9e1ea9d12def00aebaaf71e736b7b0a613ce3a6167f39e7f5dcb524b0a/ga-ctl.sock,ioSerial=/var/run/cc-oci-runtime/0241be9e1ea9d12def00aebaaf71e736b7b0a613ce3a6167f39e7f5dcb524b0a/ga-tty.sock,console=/var/run/cc-oci-runtime/0241be9e1ea9d12def00aebaaf71e736b7b0a613ce3a6167f39e7f5dcb524b0a/console.sock
I1202 11:44:45.252113   10204 vm.go:110] [vm 0241be9e hyperstart] open hyper channel /dev/vport1p1
I1202 11:44:45.252755   10204 vm.go:110] [vm 0241be9e hyperstart] send ready message
I1202 11:44:45.252836   10204 vm.go:110] [vm 0241be9e hyperstart] hyper send type 8, len 0
I1202 11:44:45.252959   10204 vm.go:110] [vm 0241be9e hyperstart] open hyper channel /dev/vport1p2
I1202 11:44:45.253124   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_init_event hyper channel event 0x61c580, ops 0x61c3e0, fd 3
I1202 11:44:45.253168   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_add_event add event fd 3, 0x61c3e0
I1202 11:44:45.253237   10204 proxy.go:73] [client #1] hyper(cmd=startpod, data={"hostname":"0241be9e1ea9","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s8","newDeviceName":"eth0","ipAddresses":[{"ipAddress":"172.17.0.2","netMask":"255.255.0.0"}]}],"routes":[{"dest":"default","gateway":"172.17.0.1","device":"eth0"},{"dest":"172.17.0.0","device":"eth0"}]})
I1202 11:44:45.253265   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_init_event hyper ttyfd event 0x61c548, ops 0x61c3c0, fd 4
I1202 11:44:45.253272   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_add_event add event fd 4, 0x61c3c0
I1202 11:44:45.254044   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_loop epoll_wait 1
I1202 11:44:45.254067   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_handle_event get event 1, he 0x61c580, fd 3. ops 0x61c3e0
I1202 11:44:45.254096   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_handle_event event EPOLLIN, he 0x61c580, fd 3, 0x61c3e0
I1202 11:44:45.254138   10204 vm.go:110] [vm 0241be9e hyperstart] hyper_channel_read
I1202 11:44:45.254165   10204 vm.go:110] [vm 0241be9e hyperstart] hyper send type 14, len 4
I1202 11:44:45.254231   10204 vm.go:110] [vm 0241be9e hyperstart] get length 303
I1202 11:44:45.254270   10204 vm.go:110] [vm 0241be9e hyperstart] hyper send type 14, len 4
I1202 11:44:45.254363   10204 vm.go:110] [vm 0241be9e hyperstart] 0 0 0 1 0 0 1 2f 7b 22 68 6f 73 74 6e 61 6d 65 22 3a 22 30 32 34 31 62 65 39 65 31 65 61 39 22 2c 22 63 6f 6e 74 61 69 6e 65 72 73 22 3a 5b 5d 2c 22 73 68 61 72 65 44 69 72 22 3a 22 72 6f 6f 74 66 73 22 2c 22 69 6e 74 65 72 66 61 63 65 73 22 3a 5b 7b 22 64 65 76 69 63 65 22 3a 22 65 6e 70 30 73 38 22 2c 22 6e 65 77 44 65 76 69 63 65 4e 61 6d 65 22 3a 22 65 74 68 30 22 2c 22 69 70 41 64 64 72 65 73 73 65 73 22 3a 5b 7b 22 69 70 41 64 64 72 65 73 73 22 3a 22 31 37 32 2e 31 37 2e 30 2e 32 22 2c 22 6e 65 74 4d 61 73 6b 22 3a 22 32 35 35 2e 32 35 35 2e 30 2e 30 22 7d 5d 7d 5d 2c 22 72 6f 75 74 65 73 22 3a 5b 7b 22 64 65 73 74 22 3a 22 64 65 66 61 75 6c 74 22 2c 22 67 61 74 65 77 61 79 22 3a 22 31 37 32 2e 31 37 2e 30 2e 31 22 2c 22 64 65 76 69 63 65 22 3a 22 65 74 68 30 22 7d 2c 7b 22 64 65 73 74 22 3a 22 31 37 32 2e 31 37 2e 30 2e 30 22 2c 22 64 65 76 69 63 65 22 3a 22 65 74 68 30 22 7d 5d 7d 
I1202 11:44:45.254386   10204 vm.go:110] [vm 0241be9e hyperstart]  hyper_channel_handle, type 1, len 303
I1202 11:44:45.254429   10204 vm.go:110] [vm 0241be9e hyperstart] call hyper_start_pod, json {"hostname":"0241be9e1ea9","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s8","newDeviceName":"eth0","ipAddresses":[{"ipAddress":"172.17.0.2","netMask":"255.255.0.0"}]}],"routes":[{"dest":"default","gateway":"172.17.0.1","device":"eth0"},{"dest":"172.17.0.0","device":"eth0"}]}, len 295
````

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by chavafg** [comment]
qa-failed

**Comment by dlespiau** [comment]
Test are reporting the "usual" 2.1 failures, also:

Fixes: https://github.com/01org/cc-oci-runtime/issues/499

**Comment by jcvenegas** [comment]
lgtm

**Comment by jcvenegas** [comment]
Really useful! merging :)

**Pull request merged**
