### PR TITLE
Networking: Explicitly set the network device to virtio-net-pci

### PR DESCRIPTION
**Pull request by mcastelino**
Explicitly set the network device to virtio-net-pci.

Note: On the host you need a kernel with CONFIG_VHOST_NET=y and
in the guest you need a kernel with CONFIG_PCI_MSI=y

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Could you add the requirement to have `CONFIG_VHOST_NET=m|y` to the README (maybe in https://github.com/01org/cc-oci-runtime/blob/master/README.rst#requirements?)

(Ideally, there would be a way to query this on a running system so that we could add a check to:  https://download.clearlinux.org/current/clear-linux-check-config.sh).

**Comment by mcastelino** [comment]
@jodh-intel Updated documentation to reflect vhost_net requirement. Update to the check script queued in your inbox for review.

**Comment by jodh-intel** [comment]
lgtm.

**Comment by jcvenegas** [comment]
+1

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
