### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by miguelinux**
This pull request is to fix the vm.json to be a json well formatted and add some files to the gitignore file.

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by dlespiau** [comment]
lgtm

**Comment by dlespiau** [comment]
@chavafg I'm not seeing a result from CI, something bad happened?

**Comment by chavafg** [comment]
@dlespiau, as @miguelinux is currently not part of the CC team in github, the CI prevented to do the testing. I added to my whitelist, but It would be good if someone adds him to the team.

**Comment by dlespiau** [comment]
@chavafg ah, but then we should have kept the logic that still starts the tests when there are 2 lgtms

**Comment by grahamwhaley** [comment]
@chavafg - we cannot add @miguelinux to the project until he has been added to the 01org github organisation - pm me if you need details of how to make that happen.

**Pull request merged**
