### PR TITLE
Tests: Enable tests that were blocked and update for popular containers

### PR DESCRIPTION
**Pull request by GabyCT**
images

Enable tests that were blocked by issue 222
Update tests (addition with --rm option)

Signed-off-by: Cervantes Tellez, Gabriela <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-failed

**Comment by GabyCT** [comment]
qa-passed

**Comment by dlespiau** [comment]
lgtm

**Comment by amshinde** [comment]
lgtm

**Pull request merged**
