### PR TITLE
2.1.0-rc.3 release

### PR DESCRIPTION
**Pull request by sameo**
- Added docker tests for handling pipe input
- Added pprof data export through HTTP
- Fixed CRI-O exec support
- Fixed shim atexit return value
- Fixed docker pipe inout handling (Issue #506)
- Fixed version functional test

Shortlog:

c22f33f proxy: Do not set the process CWD if it's empty
dbc634d oci: Build an accurate pod pointer before exec'ing
42acfd9 tests: Add explicit checking for stdout and stderr redirection tests.
a5a4f2d tests: Add docker test for handling stdin from pipe.
ba6e92d proxy: Add a way to serve pprof data over HTTP
80ceb96 shim: Add file descriptors at specifix index.
5d7ac88 shim: Handle stdin in non-tty case.
73e7d95 shim: atexit returns 0 if successful
baca26f test: Fix version functional test
6be54d4 tests: fix cc_oci_setup_shim test

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
lgtm

**Comment by dlespiau** [comment]
It may be nice to maintain a NEWS file or equivalent with the summary you've given in the PR.

**Comment by sboeuf** [comment]
@dlespiau that's a good idea to summarize each release news, but I would maybe name this file RELEASES instead of NEWS.

**Comment by sboeuf** [comment]
LGTM

**Comment by sameo** [comment]
@dlespiau Good point, NEWS file added
@sboeuf `NEWS` is a GNU standard, so we may want to stick to that.

**Comment by sboeuf** [comment]
@sameo Ah I didn't know that, let's go for NEWS then !

**Pull request merged**
