### PR TITLE
data: boot using cc-agent.target

### PR DESCRIPTION
**Pull request by jcvenegas**
This patch changes the container.target to
cc-agent.target for 2.1 support.

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm.

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
pullapprove seems to be stuck again...

lgtm.

**Comment by dlespiau** [comment]
lgtm

**Pull request merged**
