### PR TITLE
ci: Send Travis notifications to Slack

### PR DESCRIPTION
**Pull request by sameo**
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Looks like we lost some comments in `.travis.yml`. There are admittedly not super-important and will still be in the history but was this intentional?

**Comment by sameo** [comment]
@jodh-intel No, it was not intentional. The travis token encryption cli changes the `.travis.yml` file and seems to be too aggressive on the reformatting. Let me fix that up.

**Comment by sameo** [comment]
@jodh-intel Comments are back.

**Comment by jodh-intel** [comment]
@sameo - thanks.

lgtm.

**Comment by chavafg** [comment]
qa-failed

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
