### PR TITLE
Add pullapprove support

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by dlespiau** [comment]
I think PRs shouldn't have merge commits in them but be rebased against master and force pushed instead.

**Comment by dlespiau** [comment]
otherwise, lgtm!

**Comment by jodh-intel** [comment]
Re-pushed with rebase.

**Comment by grahamwhaley** [comment]
lgtm - but oddly seems to have failed the CLANG build. I'm guessing that is a spurious fail, but could you check that for us? (if it is spurious, then that could get annoying...)
I also presume pullapprove does not come into action until we have registered it and let it create its hooks - which I'm also guessing you will do after the merge :-)

**Comment by jodh-intel** [comment]
Yep - the clang error was transient. I've raised #155 to capture that problem. And yes, I'll register the project with pullapprove after this merge...

**Pull request merged**
