### PR TITLE
ci: Split go static checks so developers can invoke them

### PR DESCRIPTION
**Pull request by dlespiau**
Instead of waiting for travis to tell me I've done something wrong, fix
it and try my luck again with the other static tests, it'll be faster to
run them locally beforehand. To be used as:

  # .ci/ci-go-static-checks.sh

Or

  # .ci/ci-go-static-checks.sh ./proxy

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-failed

**Comment by jcvenegas** [comment]
This looks good, but ci is a hidden directory,  I wonder if we could document somewhere this or move the static checks to makefile.am

**Comment by chavafg** [comment]
qa-passed

**Comment by sboeuf** [comment]
LGTM

**Comment by dlespiau** [comment]
fwiw, working on making this a bit better (download/update the tools automatically and have a Makefile target.

**Comment by dlespiau** [comment]
PR updated:

- refactored a bit the code so the go checks script is really standalone and can download its dependencies
- added Makefile target to trigger the go tests locally

**Comment by amshinde** [comment]
lgtm

**Pull request merged**
