### PR TITLE
docs: Add the Sphinx documentation builder.

### PR DESCRIPTION
**Pull request by rcaballeromx**
Sphinx provides a builder which allows us to generate several different
publication outputs, share content across multiple documentations, add
cross-references within a file and across files, reuse content, test
code snippets and external links, and integrate with other systems.

Using Sphinx, we can create a content structure and cherry-pick the
content that makes it to the website.

To build the html version of the documentation, make sure to have Sphinx
installed and  just enter `make html` within the documentation folder.
The generated html can be found inside the _build folder.

For further information on Sphinx visit www.sphinx-doc.org

Signed-off-by: Rodrigo Caballero <rodrigo.caballero.abraham@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Hi @rcaballeromx, in the case we would like to use this tool , would be neede to move all our documentation format as well ?  ( currently it is Markdown )

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
qa-passed

**Comment by rcaballeromx** [comment]
Yes @jcvenegas, changing the content from MD to ReST is a necessary step and the decision has been made to follow this path. I would love to be able to accept content contributions in any format and then transform them but that process is impossible considering our limited resources for documentation.

**Comment by jodh-intel** [comment]
Hi @rcaballeromx - if we're only going to use ReST (which I love ;-), then before this PR is accepted we probably need a PR to convert the existing markdown doc to ReST.

Looks like this pretty much does it:

```
(cd documentation && for file in *.md; do pandoc -f markdown_github -t rst -o ${file/.md/.rst} "$file"; done)
```

**Comment by sameo** [comment]
@rcaballeromx I would appreciate if you could explain why moving to ReST is a necessary step. Also when and by who has this decision been made ?
The vast majority of the github hosted documentation is markdown based, and although I agree ReST is superior and allows for producing better documentation, it's definitely not as readable and simple as markdown. Which features of ReST do we currently need that are not provided by md ?

**Comment by grahamwhaley** [comment]
Given our offline conversations, we have not yet decided if:
 - We need an in-tree solution for converting .rst files to other formats
    - and if we do have an in-tree solution, if that be `sphinx` or `rst2xxx` or some other tooling

Until we've talked over and come to a consensus, let's keep this on hold for now

**Comment by jodh-intel** [comment]
Due to the fact that github does not support rST fully (and doesn't support sphinx extensions), I suggest we close this PR. Comments?

**Comment by grahamwhaley** [comment]
Agreed. I believe that also fits with @rcaballeromx current plans.

**Comment by rcaballeromx** [comment]
@grahamwhaley @jodh-intel 
Mike Tullis and I are looking into options to extend Sphinx to support Git-flavored MD with the functionalities we need.
My current short-term plan is to leave the bulk of the content in MD and in the GitHub repo.
The notable exception here are the installation and getting started guides. Those will be transformed to ReST, moved to the website's repo, tagged with the appropriate release, and replaced in GitHub with a link to the published version on the website. Luckily, I am getting some help soon and I shall be able to start this process then.

**Comment by grahamwhaley** [comment]
@rcaballeromx thanks for the update. I think we can close this PR as 'out of date' now though can't we?

**Comment by dlespiau** [comment]
@grahamwhaley I agree, seems like we can close this one.

**Pull request closed without merging**
