### PR TITLE
data: remove 2.0 systemd files

### PR DESCRIPTION
**Pull request by jcvenegas**
This patch removes old systemd files need for CC 2.0

The only services that now are required are:

cc-agent.target: File for systemd systems that starts cc-agent.service

cc-agent.service: launch the Clear Containers VM agent.

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @jcvenegas - could you add a bit of detail to the commit message explaining that hyperstart now takes care of the mounts for us?

**Comment by gorozco1** [comment]
lgtm

**Comment by gorozco1** [comment]
@jcvenegas this still is do not merge?

**Comment by jcvenegas** [comment]
@gorozco1  I forgot to remove the label, removed :P , @jodh-intel added comments in commit

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
