### PR TITLE
remove unused files

### PR DESCRIPTION
**Pull request by egernst**
data/dockerFiles/ is no longer used and is also becoming out of
date.  These now live in github.com/clearcontainers/dockerfiles

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm

**Comment by chavafg** [comment]
We need to remove the references to
```
data/dockerFiles/Dockerfile.fedora
data/dockerFiles/Dockerfile.fedora.in
data/dockerFiles/Dockerfile.ubuntu 
data/dockerFiles/Dockerfile.ubuntu.in
```
in the `Makefile.am`

**Comment by chavafg** [comment]
Also lines 5 and 6 from `versions.txt` can be removed
```
docker_fedora_version=24
docker_ubuntu_version=16.04
```
as they were used for generating the Dockerfiles that are being deleted.

**Comment by egernst** [comment]
@chavafg  - thanks -- repushed with this included.

**Comment by chavafg** [comment]
One last that I previously forgot:
Lines 259,261 from `configure.ac` can also be removed:
https://github.com/01org/cc-oci-runtime/blob/master/configure.ac#L259

Thanks.

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Once `configure.ac` is updated as mentioned by @chavafg, this should be good to go.

**Comment by egernst** [comment]
@chavafg  ; @jodh-intel -- done

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @rcaballeromx - could you review this please?

**Pull request merged**
