### PR TITLE
version: Update version for container image

### PR DESCRIPTION
**Pull request by amshinde**
This image has the hyperstart changes for accepting and
applying iptable rules.This corresponds to hyperstart
commit id cbdf6f5

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
Required for PR #825.
@chavafg Can you test PR #825 with this image and check if the Swarm tests pass wrt to port forwarding.

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Hi @amshinde - please could you add details of the specific hyperstart version (commit id) that introduced the iptables rules handling in your commit message to help with tracking.

**Comment by amshinde** [comment]
@jodh-intel I have added the hyperstart commit id in the commit message.

**Comment by jodh-intel** [comment]
Thanks @amshinde.

lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
Please can you specify the new kernel version in the commit message.

**Comment by amshinde** [comment]
@jodh-intel Updated

**Comment by jodh-intel** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
