### PR TITLE
CI: Reduce pullapprove requirements

### PR DESCRIPTION
**Pull request by grahamwhaley**
Whilst we work out some niggles with workflow, pushes, acks and QA, reduce the strictness of some pullapprove requirements.

### CODE REVIEW

**Comment by dlespiau** [comment]
With the sob tags :)

lgtm

**Comment by jcvenegas** [comment]
lgtm

**Comment by dlespiau** [comment]
grmbl

lgtm

**Comment by chavafg** [comment]
I think this does not needs ci tests, so  qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
alright, let's try that

**Pull request merged**
