### PR TITLE
ci: Revert "CI: Add script to perform basic checks on commits."

### LINKED ISSUE #882: Travis CI fails when master is tested
When ci build is not a PR should not check for 'Fixes' message

### PR DESCRIPTION
**Pull request by jcvenegas**
Check 'Fixes' message breaks travis when running on master,
lets revert  the ci check  by now.

Fixes #882
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
```
ERROR: ci-pre-checks.sh: commit 42981ebac72df01d52d0a0827d871e43297f3508: body line too long (length 78, max 72):
  'Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>'
```

I did laugh at that one.

**Comment by dlespiau** [comment]
The line length test is broken in general as well, it's not unusual to have to paste backtraces that go over the 72 chars limit. You shouldn't need to change your name to pass a test :)

**Comment by jcvenegas** [comment]
@dlespiau ,  I was planning to change my name to Charlie V but revert is also an option, so I reverted the change and used my usual BIG name in commit .

**Comment by chavafg** [comment]
qa-passed

**Comment by devimc** [comment]
lgtm

**Comment by amshinde** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
