### PR TITLE
commands: Remove unused and unfunctional attach command

### PR DESCRIPTION
**Pull request by devimc**
This patch removes all code releated with attach command.
Attach command is not part of OCI specification and
with new changes comming it is not more needed in cor

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
lgtm

**Comment by jodh-intel** [comment]
It's great to see code being deleted. But, `attach` is still being used by some of the tests (`start.bats`, `pause.bats`). Since `attach` is currently the only way to reconnect to a running container, I wonder if we should retain this code until we land the re-architecture changes. The alternative is to rework those tests to shutdown the container in other ways.

**Comment by jcvenegas** [comment]
@devimc could you please move this PR to rearch-2.1

**Comment by jodh-intel** [comment]
Hi @devimc - can the `do-no-merge` label be removed for this PR now?

**Comment by devimc** [comment]
Hi @jodh-intel  yes
once this PR is merged , I'll fix functional tests that depend of attach

**Comment by dlespiau** [comment]
We shouldn't merge this PR is it's going to make tests fail. It'd need to be part of a PR that also takes care of fixing the tests.

**Comment by chavafg** [comment]
qa-failed

**Pull request closed without merging**
