### PR TITLE
Move hyperstart mock to virtcontainers

### PR DESCRIPTION
**Pull request by sboeuf**
This commit remove all code related to the hyperstart mock because
the same code has been added to virtcontainers project.
The proxy_test.go relying on this mock is now using the mock
from virtcontainers.
It fixes issue #396.

### CODE REVIEW

**Comment by sboeuf** [comment]
We need to wait the change adding the mock hyperstart before we can merge this PR. Travis will not fail anymore after it is merged in Virtcontainers.

**Comment by sameo** [comment]
The mock package is now merged into virtcontainers.

**Comment by grahamwhaley** [comment]
Just to clarify @sboeuf , this PR relies on #422 being merged first before CI will pass, correct?

**Comment by sboeuf** [comment]
@grahamwhaley the PR #424 does not need #422. It can be merged independently. I don't know how to do that but it would be good to trigger another CI pass on this PR because the mock hyperstart has just been merged into virtvcontainers.

**Comment by grahamwhaley** [comment]
@sboeuf CI restarted - you go to the 'Details' link, and there is a 'restart tests' button. I thought it might not work for me - but seemed to .... so now we wait :-)

**Comment by dlespiau** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
lgtm.

**Comment by jodh-intel** [comment]
@sboeuf - it looks like something strange has happened on this PR as pullapprove has "stalled". Could you try closing and re-opening this PR so we can re-ack and merge?

**Comment by jodh-intel** [comment]
pullapprove has no knowledge of this PR, which might suggest a transitory github issue or a pullapprove issue. See #422 for another odd example of pullapprove behaviour.

**Comment by jodh-intel** [comment]
Merged after toggling problematic Pullapprove webhook.

**Pull request merged**
