### PR TITLE
Revert user support

### PR DESCRIPTION
**Pull request by amshinde**
Removing all user support, since this is causing issues with interactive runs.
This is likely a permission issue with the terminal.

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by amshinde** [comment]
Turned out this was a bug in the stateless patch I had sent out for hypertstart. Hyperstart does not exit on error conditions cleanly though,  showing errors at other places.

PR for the bug fix here:
https://github.com/clearcontainers/hyperstart/pull/8

**Comment by sameo** [comment]
@amshinde Nice. Can you close this PR if it's not needed anymore ?

**Pull request closed without merging**
