### PR TITLE
Resource leak fix and some code cleanup

### PR DESCRIPTION
**Pull request by amshinde**
The title should be more descriptive.. IMHO

### CODE REVIEW

**Comment by jodh-intel** [comment]
These two commits should be prefixed by the subsystem first ("logging").

**Comment by grahamwhaley** [comment]
I agree. @amshinde , can you prefix with the subsystem, and also could you expand the PR message a bit more please - 'Fixes' is too generic and short.
@jodh-intel , once the text is correct, how is the code? It lgtm

**Comment by jodh-intel** [comment]
@grahamwhaley - yep, code lgtm.

**Comment by dlespiau** [comment]
Missing the s-o-b tags as well.

For error paths, using the Linux style ones should really be the only way I'm afraid: Chapter 7 of https://www.kernel.org/doc/Documentation/CodingStyle.

**Comment by grahamwhaley** [comment]
Oh, good catch @dlespiau  I knew there would come a day when I didn't spot one of those.
It is also referenced in our https://github.com/01org/cc-oci-runtime/blob/master/CONTRIBUTING.md#certificate-of-origin

**Comment by grahamwhaley** [comment]
And on error paths - yes, that did occur to me when reading the patches. @jodh-intel , do you have thoughts on this - always use the goto:error method for any depth of nest?

**Comment by jodh-intel** [comment]
I'd personally have written this without the `else { ... }` - just test for error, and if found call `g_critical()`, then immediately return. That code is then simpler and hence easier to understand, but also less indented in the non-error case.

Certainly, for >1 error branches, we should prefer `goto error` to handle cleanup and avoid duplicated code. I'm adding that to #103.

**Comment by amshinde** [comment]
grahamwhaley: Missed out on the signed off tag. I have added it to my git alias now so I don't forget :)

**Comment by grahamwhaley** [comment]
Hi. I think these lgtm enough now, thanks for the cleanups.
@amshinde , can you ack that you took note of the exit path error handling recommendations from @dlespiau for the future? :-)

https://www.kernel.org/doc/Documentation/CodingStyle.
http://eli.thegreenplace.net/2009/04/27/using-goto-for-error-handling-in-c

thanks!

**Comment by amshinde** [comment]
@grahamwhaley yes,  took note of it :)

**Comment by amshinde** [comment]
@dlespiau any comments on the reworked patch?

**Comment by dlespiau** [comment]
oh, sorry, I didn't realise it has changed. lgtm.

**Pull request merged**
