### PR TITLE
Process: Ignore SIGPIPE when running hooks.

### PR DESCRIPTION
**Pull request by jodh-intel**
If a hook process is not expecting to be passed state on its stdin and
exits before the runtime has had a chance to pass the state to the
child, the runtime will be sent SIGPIPE, causing it to be terminated.

To avoid this, disable SIGPIPE when running the hooks.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This should fix #327.

**Comment by dlespiau** [comment]
okay, let's try again :)

lgtm

**Comment by dlespiau** [comment]
(there's a compilation warning spotted by travis to fix though)

**Comment by jodh-intel** [comment]
Fixed.

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
Closing in favour of the global solution on #486.

**Pull request closed without merging**
