### PR TITLE
Docs: Added details of functional and integration tests.

### PR DESCRIPTION
**Pull request by jodh-intel**
The DESIGN doc covered unit tests, but did not mention functional or
integration tests.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
lgtm

**Comment by devimc** [comment]
:+1:

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
Careful not to merge before the qa-passed tag until we have a way to enforce that :)

**Pull request merged**
