### PR TITLE
license: rename COPYING to LICENSE

### PR DESCRIPTION
**Pull request by devimc**
rename COPYING to LICENSE for cc-shim and cc-proxy
to keep in alignment with the main repository license
file naming

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
They already had a license file, it was just named COPYING instead of LICENSE (which is fairly standard for GNU projects). Maybe the commit message could be reworded to not imply they did not have a license until now. No objection renaming those files though.

lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
Hi @devimc - looks like you need to update `cc_proxy_extra_dist` for the new filename. But also, we the Travis failure has also highlighted that we need a `cc_shim_extra_dist` as its `README` and `COPYING`/`LICENSE` file is missing from a `make dist` archive.

**Comment by chavafg** [comment]
make distcheck failed:
```
+ script --return -c 'sudo -E make distcheck'
Script started, file is typescript
make  dist-xz am__post_remove_distdir='@:'
make[1]: Entering directory '/home/cc-tester/go/src/github.com/01org/cc-oci-runtime'
make[1]: *** No rule to make target 'proxy/COPYING', needed by 'distdir'.  Stop.
make[1]: Leaving directory '/home/cc-tester/go/src/github.com/01org/cc-oci-runtime'
Makefile:4969: recipe for target 'dist' failed
make: *** [dist] Error 2
Script done, file is typescript
```

**Comment by grahamwhaley** [comment]
Hi @devimc . In your commit you say `rename COPYING to LICENSE which is a standard for GNU projects`, which I think implies things backwards - `COPYING` is the normal for GNU projects. We can just say 'rename COPYING to LICENSE for these projects to keep in alignment with the main repository license file naming' I think.

**Comment by grahamwhaley** [comment]
with minor nit on commit message,
lgtm

**Comment by devimc** [comment]
@jodh-intel @grahamwhaley  fixed
Thanks :)

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
