### PR TITLE
shim: Change "col" attr to "column" in the json sent for handling SIG…

### PR DESCRIPTION
**Pull request by amshinde**
…WINCH

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by dlespiau** [comment]
Still the "not ok 42 start and kill state" test failing. James is looking at that flaky failure right now.

**Comment by dlespiau** [comment]
I doubled checked the flaky test was indeed the only was failing. Given that, merging the PR.

**Comment by dlespiau** [comment]
I closed the PR instead of merging it and was wondering why "tput cols" was always telling me 80, oops..., reopening.

**Comment by dlespiau** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by dlespiau** [comment]
thanks! merged for real this time

**Pull request merged**
