### PR TITLE
Fix functional tests

### PR DESCRIPTION
**Pull request by devimc**

### CODE REVIEW

**Comment by chavafg** [comment]
qa-failed

**Comment by jcvenegas** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by chavafg** [comment]
Got a failure that should be solved by #635 and issues regarding #623 which are not related to this PR. We can merge this along with #635 to resolve functional tests issues.

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
