### PR TITLE
tests: unskip tests for docker images blocked by #318

### PR DESCRIPTION
**Pull request by amshinde**
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by dlespiau** [comment]
lgtm

We probably to have update the images on the CI system before merging this PR.

**Comment by sameo** [comment]
@chavafg Is this a failure due to the kill problem ?

**Comment by chavafg** [comment]
Yes, this is due to #593, we can merge the PR.

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
