### PR TITLE
Networking/sriov

### PR DESCRIPTION
**Pull request by sainath14**
Clear Container SR-IOv integration

This code enables COR to handle docker container life events w.r.t. passing thru the SR-IOv network interface into Clear Container. COR receives the network interface based off of a SR-IOv Virtual Function (VF) in the container namespace on a docker start/run. It passes the underlying VF to the Clear Container. On docker stop, COR makes sure it leaves the VF back in its network interface form in the host default network namespace.

### CODE REVIEW

**Comment by mcastelino** [comment]
Initial merge of working SRIOV code. This is based on a old baseline. We will move this to the virt-containers codebase. The corresponding docker plugin to test the same can be found at https://github.com/clearcontainers/sriov

**Comment by dlespiau** [comment]
This PR fails the travis tests, we shouldn't have merged it with those compilation warnings at least. Now someone needs to fix those :)

**Comment by mcastelino** [comment]
@dlespiau this is based on a old code baseline and hence on its own development/unstable branch. This is an separate code base and currently needs SRIOV based systems to pass. We will update this code to merge with 2.1 code base. However it may still not pass our current CI.

**Comment by dlespiau** [comment]
Apologies, I didn't see it was a PR for a topic branch!

**Comment by grahamwhaley** [comment]
Still a good and valid 'flag raise' though @dlespiau - thanks.

**Pull request merged**
