### PR TITLE
README: Remove limitation as a workaround has been pushed.

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by gorozco1** [comment]
Why is this being removed? the issue 17 is still open

**Comment by amshinde** [comment]
I wanted to keep it open to track the stdio issue for qemu. Meanwhile I have pushed a workaround. (I need to check if it will make getting the exit status from the container difficult which hasnt been working anyways. I havent looked at it yet.)

With the workaround merged, we no longer have the limitation and can see the correct output in docker logs.

**Comment by gorozco1** [comment]
Thanks for the explaining. 
+1

**Comment by devimc** [comment]
:+1:

**Pull request merged**
