### PR TITLE
Semver fix

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Related to #275.

**Comment by dlespiau** [comment]
Maybe you could address #275 in this PR as well, you're just one commit away from changing cc_oci_semver_cmp() to a the _full() version with compatible == true to make the check more lax (which is likely to make the runtime more robust to upstream docker changes) ?

**Comment by jodh-intel** [comment]
This PR addresses #275 as it is already specifying `compatible == true` :-)

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
oh indeed! Don't hesitate to assign the bug to you next time, I'm glad the bug is fixed and glad that I hadn't spent time on it :)

lgtm

**Comment by jodh-intel** [comment]
@dlespiau - Oh, sorry! Hadn't noticed that you'd grabbed that one :) But yes, I should have attempted to grab it explicitly either way.

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
