### PR TITLE
Changes to installation documentation for Centos

### LINKED ISSUE #926: installation guide for centOS appears stale
Installation guide for centos still references checking out runtime 2.1.0.  Can / should this be updated to latest?

### PR DESCRIPTION
**Pull request by GabyCT**
Change to the installation procedure for centos 7.0 and
changes in the installation script in order to support 2.1.9

Fixes #926.

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
this is required mainly because of this issue https://github.com/01org/cc-oci-runtime/issues/926

**Comment by chavafg** [comment]
qa-failed

**Comment by egernst** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
```
$ diff documentation/Installing-Clear-Containers-on-RHEL.md documentation/Installing-Clear-Containers-on-Centos-7.md
1c1
< # Install the Intel® Clear Containers runtime on RHEL 7.3
---
> # Install the Intel® Clear Containers runtime on Centos 7.0
```

Two points here:

- This should be approved simply because it is effectively identical to the RHEL instructions (which have already been approved).
- As a follow-up we should frankly merge the two documents into one and state the instructions cover both RHEL and CentOS (less to maintain == good! :smile:!)

@rcaballeromx - thoughts?

lgtm.

**Comment by rcaballeromx** [comment]
@jodh-intel: I reviewed the document and found nothing to change. Good work @GabyCT ! 
Regarding merging the instructions into one: That is never a good idea since readers expect to find instructions of their OS regardless of how similar they are to others. Once I move the content to the website, I can reuse the content using Sphinx while still having the published output be two different instruction sets. Thus, we have both, less maintenance and fulfillment of our users' expectations.
 
Approve

**Comment by jodh-intel** [comment]
@rcaballeromx - thanks. Note that github supports symbolic links so that we can create a single file but have 2 names for it which is perfect for the CentOS/RHEL install doc imho.

**Pull request merged**
