### PR TITLE
Fix unreliable test assertions

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Fixes #327.

**Comment by dlespiau** [comment]
lgtm

**Comment by jcvenegas** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
Seems like we still have the issue of the random failure here :( : 
```
not ok 42 start and kill state
# (from function `run_cmd' in file tests/functional/common.bash, line 289,
#  in test file tests/functional/state.bats, line 59)
#   `run_cmd "$cmd" "0" "$COR_TIMEOUT"' failed
# Running: timeout 5 /root/go/src/github.com/01org/cc-oci-runtime/tests/functional/../../cc-oci-runtime  --debug --root /tmp/tmp.XhAYM6fIac-cor-test --global-log /run/cc-oci-runtime/cc-oci-runtime.log --hypervisor-log-dir /tmp/tmp.TxNElb3lML-cor-test create  --console --bundle /var/lib/oci/bundle tests_id
# 2016-11-28T18:00:56.700828Z:4740:cc-oci-runtime:critical:hooks failed, child exiting
# 
# exit code: 141
# expected exit code: 0
# See /root/go/src/github.com/01org/cc-oci-runtime/test_start_and_kill_state.log
# Test logs: /tmp/tmp.XhAYM6fIac-cor-test
# Global log file: /run/cc-oci-runtime/cc-oci-runtime.log
# Hypervisor log dir: /tmp/tmp.TxNElb3lML-cor-test
# bats status: 0
# bats output (lines array contains 0 lines):
# BUNDLE_DIR: /var/lib/oci/bundle
# ROOTFS_DIR: /var/lib/oci/bundle/rootfs
```

**Comment by jodh-intel** [comment]
Recreated - right, this doesn't fix #327, but is still valid to merge as it removes a test race.

**Comment by chavafg** [comment]
good, then moving to qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
Let's merge then!

**Pull request merged**
