### PR TITLE
Pass debug flag to shim

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Looks good, but please can you update the commit message to include `Fixes #877` (it's currently `Fixes 877` without the hash symbol, so won't auto-close the issue afaik).

**Comment by dlespiau** [comment]
The only question I have is: are we happy with not printing errors to stderr anymore? it was quite handy and helped us notice errors that may have been silenced otherwise.

**Comment by jcvenegas** [comment]
@amshinde  @dlespiau  That  is a good  question, I agree that is a useful option, and if the user is running with debug options . In case we dont want it because could be a bit annoying we should add information  in: https://github.com/01org/cc-oci-runtime/wiki/Debugging or  https://github.com/01org/cc-oci-runtime/blob/master/shim/README.md

**Comment by amshinde** [comment]
@jodh-intel Commit message has been updated.
@dlespiau @jcvenegas Error messages will still be printed to stderr

**Comment by dlespiau** [comment]
oh!

lgtm

**Comment by jodh-intel** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
