### PR TITLE
Update pullapprove to v2

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by grahamwhaley** [comment]
lgtm

**Comment by grahamwhaley** [comment]
well, apart from pullapprove is reporting the yml as invalid :-(

**Comment by jodh-intel** [comment]
pullapprove is happy now :)

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by grahamwhaley** [comment]
lgtm

**Pull request merged**
