### PR TITLE
runtime: honour detach option in exec command

### PR DESCRIPTION
**Pull request by devimc**
Now we can exec processes in detach mode

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Hi @devimc  - nice! Could you create a `bats` test for this?

**Comment by devimc** [comment]
@jodh-intel sure :)

**Comment by devimc** [comment]
@jodh-intel  @dlespiau 
PR fixed
Thanks

**Comment by jodh-intel** [comment]
lgtm

**Comment by amshinde** [comment]
lgtm

**Comment by dlespiau** [comment]
I think we need to wait for another qa-passed form @chavafg, the latest commit adds unit tests and we want to make sure they run on CI before merging.

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
