### PR TITLE
Process: Check shim setup return values.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add additional checks for file descriptor manipulation.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by amshinde** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
