### PR TITLE
Shim: Perform check on data length returned by proxy.

### PR DESCRIPTION
**Pull request by jodh-intel**
Check to ensure data length value returned by proxy is positive before
using this value in a loop.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by grahamwhaley** [comment]
@chavafg can we check the qa status of this pls - I think that is the only thing left before the merge. thx

**Comment by chavafg** [comment]
qa-passed

**Comment by gorozco1** [comment]
👍

**Comment by amshinde** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
