### PR TITLE
CI: Update Coverity Scan token used by TravisCI.

### PR DESCRIPTION
**Pull request by jodh-intel**
Updated the security token used by TravisCI to trigger Coverity Scan
runs for https://scan.coverity.com/projects/01org-cc-oci-runtime

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
Any reason for this?

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by grahamwhaley** [comment]
lgtm

**Pull request merged**
