### PR TITLE
version: Bump the recommended version of VM image

### PR DESCRIPTION
**Pull request by dlespiau**
We added a couple of fixes to hyperstart around destroypod.

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm.

**Comment by jcvenegas** [comment]
lgtm

**Comment by sboeuf** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by sboeuf** [comment]
@chavafg, could you detail the problem with that PR ?

**Comment by chavafg** [comment]
Was tested with old image, rerunning tests with new one. This time, tests should work.

**Comment by sboeuf** [comment]
cool, thanks Salvador!

**Pull request merged**
