### PR TITLE
tests: Unskip environment test as issue #324 has been resolved.

### PR DESCRIPTION
**Pull request by amshinde**
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-failed

**Comment by jcvenegas** [comment]
lgtm

**Comment by amshinde** [comment]
@chavafg I don't see any test failures in the logs.

**Comment by sameo** [comment]
LGTM

**Comment by chavafg** [comment]
there was a false positive on a docker test:
```
not ok 3 Volume - use volume in a container 
# (in test file volume.bats, line 46) 
# `[ $status -eq 0 ]' failed 
```
moving to qa-passed

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
