### PR TITLE
tests: add support for multiple interfaces in swarm test

### PR DESCRIPTION
**Pull request by devimc**
When swarm test runs in a system with multiple network interfaces
it fails since we have to specify what interface it can use
This patch fixes this issue looking for a interface in
/sys/class/net/

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by jcvenegas** [comment]
lgtm

**Comment by sameo** [comment]
@chavafg Could we give this one another run ? This looks like a false negative ?

**Comment by chavafg** [comment]
retested, now everything passed.

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
