### PR TITLE
Tests: Verify that attaching a volume to a container works correctly

### PR DESCRIPTION
**Pull request by chavafg**
This tests create a docker volume and verify that it is attached to
a clear container correctly.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
I wonder if we can also add other scenarios, use '-v' to share a folder and a file

**Comment by dlespiau** [comment]
Yes please! can we have an additional test trying to bind-mount a single file? We recently had a bug in that area and we fixed it without unit test (oops!).

**Comment by grahamwhaley** [comment]
I'm going to:
lgtm
as imo we don't need to block adding this first test whilst we write more or improve it.

**Comment by dlespiau** [comment]
sounds good, I've created a new issue then: https://github.com/01org/cc-oci-runtime/issues/262

lgtm

**Pull request merged**
