### PR TITLE
2.1.0-rc.4 release

### PR DESCRIPTION
**Pull request by sameo**
2.1.0.rc.4:
- Added mount namespace creation
- Added functional test tap output
- Added remaining exec tests
- Added locally runnable CI static tests
- Fixed proxy file descriptor leak
- Fixed swarm tests
- Fixed coverity reported security issues

Shortlog:

08a77d8 tests: Ensure we don't leak fds in the proxy tests
2c55083 proxy: Close VM object when detecting the end of the VM process
14aa150 tests: Synchronize the goroutine sending the READY packet
3b46cc1 tests: Close the file returned by allocateIO
b493bf3 tests: Fix "attatched" typo
0b66e77 tests: Add a generic fd leak detector
9db7025 Test: Ensure that the name of a replica is not empty
2ceb18e Test: Check that files in /etc are not zeroed out after docker cp
c1ed70b Tests: Modification to the swarm tests
1d32b9c namespaces: enable mount namespace
ee826df ci: Make the gofmt test output the guilty source files
caca9fb ci: Add feedback on check progression and final status
82d4c9d oci: Remove spurious line of code in comment
38e4f52 build: Add a check-go target
e47728a ci: Provide an option to go-static-checks to skip network access
86838e3 ci: Make the go static checks script really standalone
02777cf ci: Split go static checks so developers can invoke them
519c464 tests: show functional tests output in tap format
4f7d095 Tests: Add option to specify LOG_DIR in test-campaign.sh
c204e8b security: Fixed security issues reported by scan tools
26a1927 tests: Enable the remaining docker exec tests

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-failed

**Comment by grahamwhaley** [comment]
lgtm
but let's get some feedback on that qa-failed - I expect unrelated, but best to check. (cc @chavafg )

**Comment by chavafg** [comment]
there was a false positive on a swarm test, rerunning again.

**Comment by chavafg** [comment]
Still got error #593, but at it is not related to this PR, moving to qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Pull request merged**
