### PR TITLE
Go linters and the resulting proxy fixes

### PR DESCRIPTION
**Pull request by dlespiau**
Added a few linters to the travis checks:
  - misspell
  - go vet
  - gofmt
  - golint

Of course, having never run those linters on the proxy code before, it needed a few fixes here and there for everything to be green.

### CODE REVIEW

**Comment by dlespiau** [comment]
Fixes https://github.com/01org/cc-oci-runtime/issues/346
Fixes https://github.com/01org/cc-oci-runtime/issues/347
Fixes https://github.com/01org/cc-oci-runtime/issues/348

**Comment by jodh-intel** [comment]
Nice!

+1

**Comment by grahamwhaley** [comment]
Very nice. We should make sure we apply those tools to any other go based projects as well!
lgtm
Any reason not to merge??

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
Hum there seem to still be a problem reported by the CI system:

```
/bin/sh: line 1: proxy/cc-proxy.service: No such file or directory
make[2]: *** [proxy/cc-proxy.service] Error 1
Makefile:4721: recipe for target 'proxy/cc-proxy.service' failed
```

I'll have another look (make distcheck definitely passed for me :)

**Comment by dlespiau** [comment]
Ah no, sorry, wrong branch! This is not the one supposed to fix make distcheck but the proxy static linter one. Merging then.

**Pull request merged**
