### PR TITLE
Metrics: Improve readability for iperf2 metrics

### PR DESCRIPTION
**Pull request by GabyCT**
This will separate the client and server commands as well as other
modifications

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Hi @GabyCT - could you fix the indent - looks like a tabs/spaces issue.

**Comment by GabyCT** [comment]
@jodh-intel done :)

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
there was a strange failure, now reported on #815

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Thanks @chavafg - I don't think #815 is related to this PR (it's likely related to #807), so...

lgtm.

**Comment by grahamwhaley** [comment]
Tested-By: me
lgtm

Thanks for fixing this script up as well @GabyCT - they are much more readable now.
And thanks @jodh-intel for pushing us to clean them up :-)

**Pull request merged**
