### PR TITLE
logging: Add version details to log file

### LINKED ISSUE #667: runtime should log version details to logfile
To enable easier logfile analysis/debug, the runtime should log full version details (`PACKAGE_VERSION` and `GIT_COMMIT`) for every call of the runtime.

### PR DESCRIPTION
**Pull request by devimc**
fixes #667

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by dlespiau** [comment]
Having these in every log entry seems a bit heavy handed, I think we just want that information once at the start of the runtime execution (disregarding how it's called).

**Comment by jodh-intel** [comment]
Yes, I think we could add it to the `called as` log entry:

https://github.com/01org/cc-oci-runtime/blob/master/src/main.c#L399

**Comment by devimc** [comment]
@dlespiau @jodh-intel 
PR fixed

**Comment by dlespiau** [comment]
Works for me.

lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Glad to have this useful feature in the codebase.

lgtm.

**Comment by dlespiau** [comment]
Ship it!

**Pull request merged**
