### PR TITLE
versions: Update image version to get the latest hyperstart changes

### PR DESCRIPTION
**Pull request by amshinde**
Hyperstart updated to include network configuration based on
mac address.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
Now that #762 is merged, we can get this one merged too.
LGTM

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by dlespiau** [comment]
For next time, it's probably a good idea to make the version bump part of the PR introducing the need for the new version, otherwise we have a inconsistent state where master needs a newer image than advertised.

**Pull request merged**
