### PR TITLE
kernel: update to version 4.9.32

### LINKED ISSUE #989: Update kernel to 4.9.32
On 2017-06-14 the linux lts was updated kernel version to 4.9.32

### PR DESCRIPTION
**Pull request by jcvenegas**
This patch updates the updates the kernel version and clear containers
image.

Fixes #989

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
