### PR TITLE
Add autoconf-archive as dependency

### PR DESCRIPTION
**Pull request by devimc**
ax_code_coverage.m4 and ax_valgrind_check.m4 are upstream
files maintained by GNU Autoconf Archive we should use
them instead of maintaining own/local versions

### CODE REVIEW

**Comment by dlespiau** [comment]
There is no comment on the reason(s) you'd like to do that. Mind adding those to the PR and commit messages?

**Comment by grahamwhaley** [comment]
@jodh-intel Can you verify for me this is a good thing to do away with our direct pulling in of those two modules. I think we can go either way (keep the files, or do a dep) - do you have a preference?

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
@grahamwhaley - I'd rather we use the newest versions possible.

One point to consider is whether the local changes we have made to these files (cf3e64823981b30d6a40dd57f583eb2786dc9aec and c4660de7672ee62a1bb63760c4928913afbc7edd) need to be upstreamed before we switch.

**Comment by devimc** [comment]
@jodh-intel sounds good, could you send a email to autoconf archive maintainers (autoconf-archive-maintainers@gnu.org) ? might be they will accept your changes

**Comment by jodh-intel** [comment]
@devimc - I haven't checked to see if our changes are already fixed upstream yet. But looking at those commits, if this branch can be made to run under Travis, we prolly don't need to upstream.

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
got this random failure: 
```
not ok 2 Kill container with SIGUSR1 
```
which is already reported on #828

**Comment by chavafg** [comment]
qa-passed

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
