### PR TITLE
Simplify hypervisor tag processing code by tabulating data

### PR DESCRIPTION
**Pull request by devimc**
This patch reduces code lines and makes code simpler and readable.
This patch won't decrease the calls to cc_oci_replace_string.

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Nice cleanup. Can we maybe make the subject line give more context, for example:
  'Simplify hypervisor tag processing code by tablulating data'
or similar - as currently it does not convey why this is a good thing or necessary

**Comment by grahamwhaley** [comment]
Thanks for the update.
@sameo , look good to you? If so, I'll merge.
Whilst here, just a minor nit - if/when we touch this file again then it might be nice to sort the entries in the table alphabetically, just for some extra clarity - unless there is some implicit special ordering magic going on there, in which case it should be commented :-)

**Comment by sameo** [comment]
@grahamwhaley Yes, it looks good. Please go ahead and merge it.

**Comment by grahamwhaley** [comment]
Heh, I see a typo 'tab[l]ulating' in the subject line - my typo copied from my comment. I'll see if I can do a trivial fix to that, and merge anyway.

**Pull request merged**
