### PR TITLE
docs: architecture: Add DAX details and short history section

### PR DESCRIPTION
**Pull request by grahamwhaley**
Extend the architecture documentation:
- Add a DAX section and diagram in an appendix
- Add a short history section for V1.0 and V2.0

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
@grahamwhaley The diagram shows different fonts and unaligned boxes. Did you use google docs to generate it ?

**Comment by grahamwhaley** [comment]
@sameo I didn't, I used LibreOffice. I did notice the unaligned (or what looked to be not-quite-square) boxes. I'll also note that I could not match the blue in the rootfs box either. I'll go try on google slides and see if I can improve it... expect an update....

**Comment by grahamwhaley** [comment]
@sameo DAX diagram updated (to note everybody else - via google docs) - thanks. Updated both the .png and the .odp.

**Comment by jodh-intel** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Pull request merged**
