### PR TITLE
Run functional tests in travis

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by grahamwhaley** [comment]
lgtm
Adding a whole gcc build - ouch!  Makes me think of #114 again...

**Comment by jodh-intel** [comment]
Indeed. This isn't ideal.

In fact, I'm hitting Travis limits on log size (4 MB), but more frustrating is the time it takes to build gcc 6 in Travis - this, coupled to running qemu with emulation is going to seriously impact the PR turnaround time unless we can find a solution to #114.

**Comment by jodh-intel** [comment]
Fixes #255.

**Comment by jodh-intel** [comment]
Travis is now falling over as it's taking too long to build (gcc), so now looking at the caching options... :)

**Comment by jodh-intel** [comment]
This approach is proving to be non-viable. Closing to allow investigations of a better approach.

**Pull request closed without merging**
