### PR TITLE
Explain process socket

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by devimc** [comment]
:+1:

**Comment by dlespiau** [comment]
lgtm

**Comment by chavafg** [comment]
qa-passed

**Comment by gorozco1** [comment]
lgtm

**Comment by jodh-intel** [comment]
Trying a test to ensure that ...

```
author_aproval:
  ignored: true
```

... still works as expected now that we're using pullapprove v2...

This should *NOT* result in an approval...

lgtm.

**Comment by dlespiau** [comment]
lgtm

**Pull request merged**
