### PR TITLE
Reduce length of runtime dir

### LINKED ISSUE #283: hypervisor.sock file name is not complete using docker
When a container is created using docker ,  hypervisor.sock file name  in  state dir  is not complete:

The file is named hypervisor.s instead of hypervisor.sock

To reproduce this run:
docker run -ti debian
 check the container the file name in the container sate dir : 
ls run/opencontainer/containers/CONTAINER_ID/hypervisor.s
instead of : 
/run/opencontainer/containers/CONTAINER_ID/hypervisor.sock

### PR DESCRIPTION
**Pull request by jodh-intel**
Fixes #283

### CODE REVIEW

**Comment by devimc** [comment]
:+1:   
(runc uses its package name too /run/runc/)

**Comment by amshinde** [comment]
lgtm

**Comment by jodh-intel** [comment]
Yep - could you either raise a PR or raise an issue for this?

**Comment by dlespiau** [comment]
Let's start with an issue.

**Pull request merged**
