### PR TITLE
Metrics: Network Measurement using Iperf

### PR DESCRIPTION
**Pull request by GabyCT**
This script will measure network bandwidth, jitter, network bandwidth
for multiple TCP connections, UDP network bandwidth and bi-directional
network bandwidth using iperf in a local setup (1 client - 1 server in
the same hardware).

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by grahamwhaley** [comment]
Looking pretty good to me. A couple of notes:
- we are using an image from a user on the docker hub, which is probably fine for now, but we should be aware that maybe that will go away one day, and we should have our own image setup
- that image is using iperf2 I think. I wonder if iperf3 is actually better - @mcastelino any thoughts on that?
- I ran the test locally and the UDP test bandwidth is 3000x less than the TCP (1mbit vs 3gbit) - is that expected, do you see that locally as well etc. Just feels like a big gap, so would be good if we verified that is the expected result.

otherwise,
lgtm

**Comment by GabyCT** [comment]
@grahamwhaley the main reason why we are using iperf2 is because iperf3 is not working with cc-oci-runtime (issue #152). On the other hand, I saw the same behaviour in UDP (locally).

**Comment by egernst** [comment]
I see same delta in performance when I run TCP v UDP locally as well.  I expect this is a result of packet sizes being used in tcp (1500) vs in UDP (not sure what's used, but guessing much smaller, individual packets).  Perhaps Manohar can comment here.  Also depends if we are getting packet drops, etc.

**Comment by mcastelino** [comment]
@GabyCT @grahamwhaley We should use our own image.
iperf2 has one feature that is missing in iperf3 which is the reason I still want this to be used for that one test case. So we need both iperf3 and 2.

> Bi-directional simultaneous (test the speed both ways at the same time)
> Use the -d switch to test in the network bandwidth in both directions. This will perform two tests; one from local host to remote host, and another from the remote host to the local host

We use/should test this. 

iperf3 is better at UDP testing as iperf2 does not reliably support testing UDP beyond 2Gbps

> Note that iperf 2.x results are inconsistent for UDP above 2Gbps. We recommend using nuttcp or iperf3 for high-speed UDP testing.


@GabyCT can you use iperf UDP test itself to measure jitter vs ping as this allows for better control

> The UDP tests with the -u argument 

@egernst @GabyCT 

If we really want to measure UDP bandwidth then you need to scale it up till we see loss with iperf3.
But that will require that this script be modified to perform a scaled search.

Better yes let us switch to 

> nuttcp 

for UDB bandwidth testing

**Comment by GabyCT** [comment]
@mcastelino, I did the implementation in this script for iperf2 and create an image in docker hub. Currently, this script measures bi-directional (local-remote) and (remote-local), also it is measuring jitter using -u option, bandwidth and multiple tcp connections. @mcastelino, @grahamwhaley, @egernst, I will create another PR for the implementation of iperf3 and the use of nuttcp.

**Comment by egernst** [comment]
Sounds good to me. Thanks!

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-passed

**Comment by grahamwhaley** [comment]
Just a check then - are we waiting for changes to this PR, or are we going to merge this one and then add improvements on top? @GabyCT @egernst

**Comment by GabyCT** [comment]
@grahamwhaley improvements and new tests will be on top

**Comment by grahamwhaley** [comment]
OK, then given the 'promise' we will do updates (maybe you could open an Issue for that @GabyCT ?),
lgtm

**Comment by GabyCT** [comment]
@grahamwhaley done :) #791

**Comment by amshinde** [comment]
lgtm

**Comment by grahamwhaley** [comment]
Hi @mcastelino @GabyCT - (comment on old thread, which may lead us to open a new issue...) - now we have iperf3 and nuttcp tests in place, I get the feeling that all but one of the iperf2 tests/measures are probably now redundant and outdated? If so, can we state which iperf2 test is the one we need to keep, and then rework the iperf2 script to remove (or disable by default) all the tests we don't need any more?
It is quite confusing having multiple tests that report say jitter or UDP bandwidth *if* they are duplications (that is, unless they add something unique - in which case I think we need to document that much more clearly).

**Comment by mcastelino** [comment]
@grahamwhaley @GabyCT The only iperf2 test we need to retain is the directional test where both ends act as server and client. All remaining tests should be run just with iperf3. There is no value running them with iperf2.

Bidirectional testing (-d / -r)

**Comment by GabyCT** [comment]
@mcastelino and @grahamwhaley so I will submit a PR where I will remove the other tests and only retain the bidirectional test

**Comment by jodh-intel** [comment]
Related: #848.

**Pull request merged**
