### PR TITLE
tests: generate test-common.bash for docker-tests

### PR DESCRIPTION
**Pull request by dvoytik**
Otherwise 'make docker-tests' breaks.

Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
@dvoytik - thanks for your contribution!

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
