### PR TITLE
ciao-vendor support 

### PR DESCRIPTION
**Pull request by dlespiau**
The plan has always been to try to use ciao-vendor for cc-oci-runtime. It wasn't quite read though until earlier this week: https://github.com/01org/ciao/pull/778

I also needed a couple of tweaks in this repository to make it work, nothing major really, but now:
```
$ ciao-vendor deps
Package Root			Repo						Version		License
github.com/davecgh/go-spew	https://github.com/davecgh/go-spew.git		6d212800	ISC
github.com/hyperhq/runv		https://github.com/hyperhq/runv.git		28d48ac6	Apache v2.0
github.com/pmezard/go-difflib	https://github.com/pmezard/go-difflib.git	792786c7	BSD
github.com/stretchr/testify	https://github.com/stretchr/testify.git		976c720a	MIT

$ ciao-vendor check
All Dependencies Known: [OK]
All Dependencies Installed: [OK]
All Dependencies Vendored: [OK]
All Dependencies Used: [OK]

$ ciao-vendor updates
Updating non-vendored dependencies
github.com/davecgh/go-spew (download)
github.com/hyperhq/runv (download)
github.com/pmezard/go-difflib (download)
github.com/stretchr/testify (download)
Package				Status			
github.com/davecgh/go-spew	6 commits behind HEAD	
github.com/hyperhq/runv		33 commits behind HEAD	
github.com/pmezard/go-difflib	Up to date		
github.com/stretchr/testify	Up to date
```

### CODE REVIEW

**Comment by jodh-intel** [comment]
There are a couple of confusing typos in the commits:

- 473cb91b24ccf603e27a5f243f1070490086d8a9: `s/than cia/than ciao/`.


- 337a35de9264956d1024ed0fd455b071e94ed836 `s/Because that filed /Because that file /`.

**Comment by dlespiau** [comment]
Both fixed, I blame the way too short night.

**Comment by jodh-intel** [comment]
Travis is failing, but only on clang - looks like you have a stack trace there for #384.

Once a Travis rebuild is run (I left it so you can check out the log first)...

lgtm.

**Comment by dlespiau** [comment]
Right, that was the race between waitgroup's Wait() and Add(1). Hopefully have a fixed queued up for that in #392

**Comment by grahamwhaley** [comment]
I'm going to give it the:
lgtm
but will note that an explanation of what ciao-vendor simplifies or helps us do here would be nice :-)

**Comment by chavafg** [comment]
qa-failed

**Comment by dlespiau** [comment]
ciao-vendor simplifies vendoring: https://blog.gopheracademy.com/advent-2015/vendor-folder/

There are a number of alternatives, govendor being the closest to what ciao-vendor does (says Mark, the author of ciao-vendor). Both of those tools could be obsoleted as soon as go 1.8 which should introduce a bit of standardisation around vendoring tooling.

**Pull request merged**
