### PR TITLE
Tests: add missing mount tests to state

### LINKED ISSUE #248: state_test.c needs to test state file mount object.
`test_cc_oci_state_file_read()` in `tests/state_test.c` needs to be updated to include tests for the mounts:

- test to read new file `state-no-mounts.json` [1]
- `state.json` needs to have a `mounts` object added to it.
- test to read `state-mounts-no-mount-destination.json`.
- test to read `state-mounts-no-mount-directory_created.json`.

Also, `test_cc_oci_state_file_create()` needs to be updated to perform checks on the mounts object in the generated state file.

Identified as missing when reviewing #231.

---
[1] - needs creating below `tests/data/`.

### PR DESCRIPTION
**Pull request by devimc**
fixes #248

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-passed

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
qa-passed

[Approved with PullApprove](https://pullapprove.com/01org/cc-oci-runtime/pull-request/249/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=01org/cc-oci-runtime) [Approved with PullApprove](https://pullapprove.com/01org/cc-oci-runtime/pull-request/249/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=01org/cc-oci-runtime)

**Comment by grahamwhaley** [comment]
@jodh-intel the qa-passed seems to be OK with this now - are you OK with the test files? If @jodh-intel has no issues, then:
lgtm

**Comment by jcvenegas** [comment]
+1

**Comment by dlespiau** [comment]
lgtm

**Pull request merged**
