### PR TITLE
docs: contrib: Fix hotlinks in contributing document

### LINKED ISSUE #857: md file hotlinks are not rendering correctly
It looks like the hotlinks in our markdown files may not be rendering correctly - possibly there has been a change on the github side that has caused this?
For instance, see the CONTRIBUTING.md file at the top level
https://github.com/01org/cc-oci-runtime/blob/master/CONTRIBUTING.md
where you can see links showing (in the cooked view) as:
```
[GPL v2 License] (https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)
```
where the (xxx) part should not be rendered at all, and the []'s should also vanish etc.

### PR DESCRIPTION
**Pull request by grahamwhaley**
Fix hotlink format in CONTRIBUTING file so it renders properly on github.
Fixes #857

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
@rcaballeromx - yeah,

**Pull request merged**
