### PR TITLE
NULL, assert and parameter checks.

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by chavafg** [comment]
qa-passed

**Comment by grahamwhaley** [comment]
lgtm
We could probably have a better subject line for the series (for the merge commit) - it's not really issues with cgroups themselves, it's more NULL, assert and parameter checks.

**Comment by grahamwhaley** [comment]
Oh, and @jodh-intel in case you are bothered, there is a typo in the first commit message: `deferenced` - meant `dereferenced` I presume?

**Comment by jodh-intel** [comment]
@grahamwhaley - ta. fixed.

**Comment by chavafg** [comment]
qa-passed

**Pull request merged**
