### PR TITLE
tests: Unskip tests for images for all issues resolved in 2.1 so far.

### PR DESCRIPTION
**Pull request by amshinde**
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
qa-failed

**Comment by jodh-intel** [comment]
The test failure seems unrelated to this PR (`volume.bats`). Also, it's not clear if that failure is a transitory issue.

@chavafg  - please could you retest this branch to see if this test failure is repeatable?

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Pull request merged**
