### PR TITLE
build: Use AM_V_GEN when generating the commit_id file

### PR DESCRIPTION
**Pull request by dlespiau**
Nicer builds are all the rage.

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
The builds have started failing with:

configure.ac:23: error: Autoconf version 2.69 or higher is required

Weird, as we didn't see that before... and we did test all the PRs

**Comment by chavafg** [comment]
I see that travis went back to ubuntu 12.04 instead of 14.04

**Comment by dlespiau** [comment]
ah! now, let's find out why

**Comment by grahamwhaley** [comment]
good spot @chavafg

**Comment by dlespiau** [comment]
Seems like we managed to catch a window where travis hit a regression and didn't honour the dist variable. Just re-triggered the build and it's now green.

**Comment by jodh-intel** [comment]
LGTM, although the commit message doesn't contain a subsystem in the first line and there isn't really an explanation of the change.

**Comment by jodh-intel** [comment]
Ah - apologies @dlespiau. Regarding my previous comment, I was looking at the comments section, not the commit header log entry.

**Comment by grahamwhaley** [comment]
@dlespiau , amusing though the commit message is :-), I too think we can do a little better with a description/explanation. Could you expand that a bit please, and then we'll merge.  Thanks!

**Comment by dlespiau** [comment]
Fair enough, updated the commit message.

**Comment by grahamwhaley** [comment]
Great, thanks :-)

**Pull request merged**
