### PR TITLE
image: Update clear container image in versions.txt.

### PR DESCRIPTION
**Pull request by amshinde**
This image contains the fix for getting rid of the LANG
environment variable fixed with the hyperstart package.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
lgtm

**Comment by gorozco1** [comment]
👍

**Comment by chavafg** [comment]
qa-failed

**Comment by chavafg** [comment]
again issue #593 affecting this result, moving to qa-passed as this is not related to that issue.

**Comment by chavafg** [comment]
qa-passed

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
