### PR TITLE
CI: Perform basic checks on PR commits.

### LINKED ISSUE #872: Create CI pre-checks script to check git commits
Create a script that performs basic checks on the new commits to be merged.

Script can check for things like a `Fixes #XXX` tag, subsystem in title, *etc*.

Script will be called as part of the CI workflow crucially before any setup/build/tests run.

See #856.

### PR DESCRIPTION
**Pull request by jodh-intel**
Use the new "checkcommits" program in the "tests" repository
to perform basic checks on PR commits, such as:

- Subject
  - Contains a subsystem.
  - Length is within prescribed limits.

- Body
  - Contains a "Fixes #XXX" comment.
  - Line lengths are within prescribed limits.

Unlike the original implementation (#873), "checkcommits" should
be more robust.

Fixes #872.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This replaces #909.

**Comment by chavafg** [comment]
qa-passed

**Comment by jodh-intel** [comment]
Blocked on https://github.com/clearcontainers/tests/pull/46.

**Comment by jodh-intel** [comment]
I seem to have hit the Travis bug **again** :sob:

**Pull request closed without merging**
