### PR TITLE
Release 2.1.12

### PR DESCRIPTION
**Pull request by jcvenegas**
## Changes                                                          
- kernel: update to version 4.9.32                                  
- build: obs: Update obs changelog for clear-containers-image       
- misc: Remove NEWS file.                                           
- artifacts: Update kernel and image for clear-containers           
- Fix docker swarm tests in docker 17                               
- build: obs: Update post release changelog                         
- docs: Update Clear Containers 2.1 Fedora docs                     
- build: Makefile: Add generate-files rule                          

## Shortlog                                                         
c0200a3 kernel: update to version 4.9.32                            
b395ad0 build: obs: Update obs changelog for clear-containers-image 
d09d4fc misc: Remove NEWS file.                                     
71d4ec2 artifacts: Update kernel and image for clear-containers     
f9b300f tests: skip flaky swarm test                                        
9c34a01 tests: replace harcoded service names to variables          
3b9fffb tests: don't wait forever for swarm replicas                
974184f tests: Add function to check when a swarm service is ready  
74683fe build: obs: Update post release changelog                   
bb492c8 docs: Update Clear Containers 2.1 Fedora docs               
eed89de build: Makefile: Add generate-files rule                    

## Compatibility with Docker                                        
Clear Containers 2.1.11 is compatible with Docker v17.05.0-ce       
## OCI Runtime Specification                                        
Clear Containers 2.1.11 support the OCI Runtime Specification [1.0.0-rc5][ocispec]                                                      

# Installation                                                      
- [Centos][centos]                                                  
- [Ubuntu][ubuntu]                                                  
- [Fedora][fedora]                                                  
- [Clear Linux][clearlinux]                                         

# Issues & limitations                                              
- Qemu segfault (free(): invalid pointer) running dnf install #669  
- DNS Resolution in Swarm #854                                      
- docker rm -f reports 'Driver devicemapper failed to remove root filesystem' #795                                                      

[centos]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Centos-7.md                  
[ubuntu]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Ubuntu.md                    
[fedora]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-Fedora-25.md
[clearlinux]: https://github.com/01org/cc-oci-runtime/blob/master/documentation/Installing-Clear-Containers-on-ClearLinux.md
[clearlinuximage]: https://download.clearlinux.org/releases/15900/clear/clear-15900-containers.img.xz                                   
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5 
Fixes: #992

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
The shortlog has an odd entry for f9b300f - stray branch information?

**Comment by chavafg** [comment]
qa-passed

**Comment by jcvenegas** [comment]
@jodh-intel  fixed, yes was extra information from my local branch

**Comment by jcvenegas** [comment]
`do-not-merge`: waiting for obs packages be generated an tested

**Comment by jcvenegas** [comment]
@chavafg http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-staging/ obs packages ready for testing.
`cc-oci-runtime` based on git commit : 64f051c
`clear-containers-image` based on 15900
`linux-container` based on `linux-4.9.32` 
http://download.opensuse.org/repositories/home:/clearlinux:/preview:/clear-containers-staging/Fedora_26/x86_64/

**Comment by chavafg** [comment]
lgtm.
All Tests passed
Versions tested:
```
cc-oci-runtime:          2.1.11 + 64f051c
clear-containers image:  clear-15900-containers.img
clear-containers kernel: vmlinux-4.9.32-62.container 
qemu-lite:               2.7.1 + git.741f430-4.1 
```

**Comment by gorozco1** [comment]
👍

**Pull request merged**
