### PR TITLE
Update Clear Containter image version

### LINKED ISSUE #649: runtime hangs in delete with an error in hyperstart (clearlinux image)
I've spent some time exercising the tests and stumbled on yet another bug:

Running:

```
for i in `seq 0 20`; do  docker run -dti clearlinux sh ; docker rm -f $(docker ps -aq) ; sleep 1; if pidof qemu-lite-system-x86_64; then break ; fi ; done
```

One of the docker rm just hangs. The processes then are:

```
root      4298  0.0  0.6 1016896 49704 pts/6   Sl+  Feb02   0:37  |   |           \_ dockerd --debug --default-runtime=cor
root      4305  0.0  0.1 581944 10412 ?        Ssl  Feb02   0:06  |   |               \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 
root     20705  0.0  0.0  44700  4404 ?        S    15:09   0:00  |   |                   \_ /home/damien/clear/install/bin/cc-oci-runtime delete 8fec0f18a8c7210181cee48ea8a12e0ce616f0340992967a46cb23f0211cb528
```

The proxy output:

```
I0203 15:09:01.026457   20496 proxy.go:67] [client #3] client connected
I0203 15:09:01.026532   20496 proxy.go:77] [client #3] attach(containerId=8fec0f18a8c7210181cee48ea8a12e0ce616f0340992967a46cb23f0211cb528)
I0203 15:09:01.026793   20496 proxy.go:77] [client #3] hyper(cmd=destroypod, data={})
I0203 15:09:01.027250   20496 vm.go:114] [vm 8fec0f18 hyperstart] hyper_loop epoll_wait 1
I0203 15:09:01.027299   20496 vm.go:114] [vm 8fec0f18 hyperstart] hyper_handle_event get event 1, he 0x41e1b0, fd 3. ops 0x41e030
I0203 15:09:01.027368   20496 vm.go:114] [vm 8fec0f18 hyperstart] hyper_handle_event event EPOLLIN, he 0x41e1b0, fd 3, 0x41e030
I0203 15:09:01.027397   20496 vm.go:114] [vm 8fec0f18 hyperstart] hyper_channel_read
I0203 15:09:01.027477   20496 vm.go:114] [vm 8fec0f18 hyperstart] hyper send type 14, len 4
I0203 15:09:01.027558   20496 vm.go:114] [vm 8fec0f18 hyperstart] get length 10
I0203 15:09:01.027627   20496 vm.go:114] [vm 8fec0f18 hyperstart] hyper send type 14, len 4
I0203 15:09:01.027735   20496 vm.go:114] [vm 8fec0f18 hyperstart] 0 0 0 4 0 0 0 a 7b 7d 
I0203 15:09:01.027785   20496 vm.go:114] [vm 8fec0f18 hyperstart]  hyper_channel_handle, type 4, len 10
I0203 15:09:01.027834   20496 vm.go:114] [vm 8fec0f18 hyperstart] get DESTROYPOD message
I0203 15:09:01.028469   20496 vm.go:114] [vm 8fec0f18 hyperstart] Sending SIGTERM
I0203 15:09:01.028543   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 190
I0203 15:09:01.028858   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 184
I0203 15:09:01.028956   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 143
I0203 15:09:01.029054   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 116
I0203 15:09:01.029109   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 111
I0203 15:09:01.029160   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 110
I0203 15:09:01.029207   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 105
I0203 15:09:01.029254   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 104
I0203 15:09:01.029307   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 98
I0203 15:09:01.029350   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 95
I0203 15:09:01.029403   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 91
I0203 15:09:01.029445   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 85
I0203 15:09:01.029499   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 84
I0203 15:09:01.029541   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 83
I0203 15:09:01.029594   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 82
I0203 15:09:01.029653   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 81
I0203 15:09:01.029701   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 80
I0203 15:09:01.029753   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 79
I0203 15:09:01.029808   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 78
I0203 15:09:01.029855   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 77
I0203 15:09:01.029902   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 76
I0203 15:09:01.029954   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 75
I0203 15:09:01.029997   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 74
I0203 15:09:01.030067   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 73
I0203 15:09:01.030109   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 72
I0203 15:09:01.030164   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 71
I0203 15:09:01.030211   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 70
I0203 15:09:01.030257   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 69
I0203 15:09:01.030309   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 68
I0203 15:09:01.030351   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 67
I0203 15:09:01.030404   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 66
I0203 15:09:01.030446   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 65
I0203 15:09:01.030499   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 64
I0203 15:09:01.030541   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 63
I0203 15:09:01.030594   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 62
I0203 15:09:01.030659   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 61
I0203 15:09:01.030696   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 60
I0203 15:09:01.030749   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 59
I0203 15:09:01.030800   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 58
I0203 15:09:01.030847   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 57
I0203 15:09:01.030894   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 56
I0203 15:09:01.030940   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 55
I0203 15:09:01.030986   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 54
I0203 15:09:01.031057   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 53
I0203 15:09:01.031107   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 52
I0203 15:09:01.031177   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 51
I0203 15:09:01.031220   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 29
I0203 15:09:01.031276   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 28
I0203 15:09:01.031319   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 25
I0203 15:09:01.031365   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 24
I0203 15:09:01.031413   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 23
I0203 15:09:01.031460   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 22
I0203 15:09:01.031507   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 21
I0203 15:09:01.031554   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 20
I0203 15:09:01.031600   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 19
I0203 15:09:01.031659   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 18
I0203 15:09:01.031706   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 17
I0203 15:09:01.031753   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 16
I0203 15:09:01.031800   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 15
I0203 15:09:01.031847   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 14
I0203 15:09:01.031893   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 13
I0203 15:09:01.031939   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 12
I0203 15:09:01.031985   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 11
I0203 15:09:01.032050   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 10
I0203 15:09:01.032089   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 9
I0203 15:09:01.032142   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 8
I0203 15:09:01.032193   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 7
I0203 15:09:01.032239   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 6
I0203 15:09:01.032286   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 5
I0203 15:09:01.032332   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 4
I0203 15:09:01.032379   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 3
I0203 15:09:01.032426   20496 vm.go:114] [vm 8fec0f18 hyperstart] kill process 2
I0203 15:09:01.035795   20496 vm.go:114] [vm 8fec0f18 hyperstart] fopen /proc/194/status
I0203 15:09:01.035926   20496 vm.go:114] [vm 8fec0f18 hyperstart] can not open process proc status file: No such file or directory

[hangs]
```

The qemu process is gone, so vm has been shutdown, presumably. A "normal" run goes:

```
I0203 15:22:27.270020   21591 vm.go:114] [vm b8f6edbd hyperstart] kill process 2
I0203 15:22:27.270155   21591 vm.go:114] [vm b8f6edbd hyperstart] fopen /proc/188/status
I0203 15:22:27.270347   21591 vm.go:114] [vm b8f6edbd hyperstart] find sigign 	0000000000285004
I0203 15:22:27.270441   21591 vm.go:114] [vm b8f6edbd hyperstart] mask is 285004
I0203 15:22:27.270522   21591 vm.go:114] [vm b8f6edbd hyperstart] signal term is ignored, kill it
I0203 15:22:27.270723   21591 vm.go:114] [vm b8f6edbd hyperstart] pid 188 exit by signal, status 9
I0203 15:22:27.270815   21591 vm.go:114] [vm b8f6edbd hyperstart] exec pid 188, pid 188
I0203 15:22:27.270907   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_exec_exit exec exit pid 188, seq 1, container b8f6edbd02d1ba1bd373a202dd918035a248d66a539be928db9f7031f9653a30
I0203 15:22:27.271052   21591 vm.go:114] [vm b8f6edbd hyperstart] container init process 188
I0203 15:22:27.271785   21591 vm.go:114] [vm b8f6edbd hyperstart] fail to stat mnt ns of process 100: No such file or directory
I0203 15:22:27.271940   21591 vm.go:114] [vm b8f6edbd hyperstart] fail to stat mnt ns of process 133: No such file or directory
I0203 15:22:27.272061   21591 vm.go:114] [vm b8f6edbd hyperstart] still have 3 user of exec
I0203 15:22:27.272155   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_loop epoll_wait 3
I0203 15:22:27.272230   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_event get event 16, he 0x1374a88, fd 12. ops 0x41e0d8
I0203 15:22:27.272307   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_event event EPOLLHUP or EPOLLERR, he 0x1374a88, fd 12, 10
I0203 15:22:27.272329   21591 vm.go:114] [vm b8f6edbd hyperstart] stderr_hup
I0203 15:22:27.272405   21591 vm.go:114] [vm b8f6edbd hyperstart] pts_hup, seq 1
I0203 15:22:27.272484   21591 vm.go:114] [vm b8f6edbd hyperstart] still have 2 user of exec
I0203 15:22:27.272505   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_event get event 16, he 0x1374a50, fd 11. ops 0x41e0f8
I0203 15:22:27.272572   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_event event EPOLLHUP or EPOLLERR, he 0x1374a50, fd 11, 10
I0203 15:22:27.272660   21591 vm.go:114] [vm b8f6edbd hyperstart] stdout_hup
I0203 15:22:27.272763   21591 vm.go:114] [vm b8f6edbd hyperstart] pts_hup, seq 1
I0203 15:22:27.272862   21591 vm.go:114] [vm b8f6edbd hyperstart] still have 1 user of exec
I0203 15:22:27.272973   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_event get event 16, he 0x1374a18, fd 9. ops 0x41e118
I0203 15:22:27.273113   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_handle_event event EPOLLHUP or EPOLLERR, he 0x1374a18, fd 9, 10
I0203 15:22:27.273139   21591 vm.go:114] [vm b8f6edbd hyperstart] stdin_hup
I0203 15:22:27.273157   21591 vm.go:114] [vm b8f6edbd hyperstart] pts_hup, seq 1
I0203 15:22:27.273289   21591 vm.go:114] [vm b8f6edbd hyperstart] last user of exec exit, release
I0203 15:22:27.273343   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_modify_event modify event fd 4, 0x41e178, event 5
I0203 15:22:27.273443   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_release_exec exit code 0
I0203 15:22:27.273529   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper_release_exec container init exited manually, remains 1
I0203 15:22:27.273550   21591 vm.go:114] [vm b8f6edbd hyperstart] hyper send type 9, len 0
I0203 15:22:27.273953   21591 vm.go:114] [vm b8f6edbd hyperstart] umount /tmp/hyper/shared
```

I've played with many things, so could be a problem on my end. Could be a problem with the proxy as well, maybe, but what's sure is that the runtime blocks until it receives an answer from the hyperstart/proxy.

### PR DESCRIPTION
**Pull request by jcvenegas**
Fixes #649 #623

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by chavafg** [comment]
qa-failed

**Comment by dlespiau** [comment]
lgtm

**Comment by dlespiau** [comment]
This PR is just the updating the version in a text file and we (unfortunately) don't have anything linked to it (like downloading the recommended version for testing).

So, we can safely ignore the CI false positive and merge.

**Pull request merged**
